name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  triage:
    if: >-
      github.event.pull_request.author_association != 'OWNER' &&
      github.event.pull_request.author_association != 'COLLABORATOR'
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "PRs are not accepted."
